targets:
  $default:
    builders:
      build_version:
        enabled: true
      build_web_compilers|entrypoint:
        generate_for:
          - web/main.dart
        options:
          compiler: dart2js
          dart2js_args:
            - -O4
            - -Ddebug=false
