targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - web/main.dart
        options:
          compiler: dart2js
          dart2js_args:
            - --fast-startup
            - --omit-implicit-checks
            - --trust-primitives
            - --minify
            - --no-source-maps
            - -Ddebug=false
