name: damacreat_io
version: 0.11.1-dev
description: Client for damacreat
publish_to: none
environment:
  sdk: '>=2.9.0 <3.0.0'
dependencies:
  dartemis: ^0.8.0
  gamedev_helpers:
    git:
      url: git://github.com/kayzgames/gamedev_helpers.git
      ref: f4cd1becea0a141ef68131ba113fb69011f229e1
  damacreat:
    git:
      url: git@bitbucket.org:isowosi/damacreat.git
      ref: tags/0.11.0
  angular: ^6.0.0-alpha
  isowosi_angular_components:
    git: git@bitbucket.org:dennis_kaselow/isowosi_angular_components
  markdown: ^2.0.2
  lawndart:
    git:
      url: git://github.com/denniskaselow/lawndart.git
      ref: b36d76770bf4771730fdcb00f925534c74be1d95
  bit_array: ^2.0.0
  aspen: ^0.3.0
  aspen_assets: ^0.3.0
dev_dependencies:
  build_runner: ^1.0.0
  build_version: ^2.0.0
  build_web_compilers: any
  sass_builder: ^2.1.1
  dartemis_builder: ^0.1.0
  aspen_builder: ^0.3.0