name: damacreat_io
description: Client for damacreat
publish_to: none
environment:
  sdk: '>=2.0.0-dev.69 <3.0.0'
dependencies:
  dartemis:
    git:
      url: git://github.com/denniskaselow/dartemis.git
      ref: feature/ddc
  gamedev_helpers:
    git:
      url: git://github.com/kayzgames/gamedev_helpers.git
      ref: feature/ddc
  damacreat:
    path: ../damacreat
dev_dependencies:
  build_runner: ^0.9.0
  build_web_compilers: any  
  dartemis_builder:
    git: git://github.com/denniskaselow/dartemis_builder.git
