name: damacreat_io
version: 0.5.1-dev.3
description: Client for damacreat
publish_to: none
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  dartemis:
    git:
      url: git://github.com/denniskaselow/dartemis.git
  gamedev_helpers:
    git:
      url: git://github.com/kayzgames/gamedev_helpers.git
      ref: games/damacreat/0.5.0
  damacreat:
    git:
      url: git@bitbucket.org:isowosi/damacreat.git
      ref: tags/0.5.0
  angular: ^5.0.0
  isowosi_angular_components:
    git: git@bitbucket.org:dennis_kaselow/isowosi_angular_components
  markdown: ^2.0.2
  lawndart:
    git:
      url: https://github.com/lejard-h/lawndart.git
      ref: 4ca04e4a703063286d0bf46b5bed378ef5e6ac34
dev_dependencies:
  build_runner: ^0.10.0
  build_version: ^1.0.0
  build_web_compilers: any
  sass_builder: ^2.1.1
  dartemis_builder:
    git: git://github.com/denniskaselow/dartemis_builder.git

dependency_overrides:
  angular:
    path: ../angular/angular