name: damacreat_io
version: 0.2.0-dev
description: Client for damacreat
publish_to: none
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  dartemis:
    git:
      url: git://github.com/denniskaselow/dartemis.git
  gamedev_helpers:
    git:
      url: git://github.com/kayzgames/gamedev_helpers.git
      ref: webgl1
  damacreat:
    path: ../damacreat
dev_dependencies:
  build_runner: ^0.10.0
  build_version: ^1.0.0
  build_web_compilers: any  
  dartemis_builder:
    git: git://github.com/denniskaselow/dartemis_builder.git
