name: damacreat_io
version: 0.5.1-dev.3
description: Client for damacreat
publish_to: none
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  dartemis:
    git:
      url: git://github.com/denniskaselow/dartemis.git
  gamedev_helpers:
    git:
      url: git://github.com/kayzgames/gamedev_helpers.git
      ref: games/damacreat/0.5.0
  damacreat:
    path: ../damacreat
  angular: ^5.0.0
  isowosi_angular_components:
    git: git@bitbucket.org:dennis_kaselow/isowosi_angular_components
dev_dependencies:
  build_runner: ^0.10.0
  build_version: ^1.0.0
  build_web_compilers: any
  sass_builder: ^2.1.1
  dartemis_builder:
    git: git://github.com/denniskaselow/dartemis_builder.git